# Copyright (C) 2009 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

LOCAL_MODULE    := VanillaWorld
LOCAL_SRC_FILES :=  \
				Core/Spline/VBSpline.c\
				Core/Spline/VBSpline2D.c\
				Core/Spline/VBSpline2DBezierCubic.c\
				Core/Spline/VBSpline2DBezierQuadratic.c\
				Core/Spline/VBSpline3D.c\
				Core/Spline/VBSplineBlend.c\
				Core/VBAABB.c\
				Core/VBArray.c\
				Core/VBArrayList.c\
				Core/VBArrayVector.c\
				Core/VBColor.c\
				Core/VBColorAdvanced.c\
				Core/VBColorG.c\
				Core/VBColorGA.c\
				Core/VBColorHSV.c\
				Core/VBColorRGB.c\
				Core/VBColorRGBA.c\
				Core/VBEasing.c\
				Core/VBLine2D.c\
				Core/VBMath.c\
				Core/VBMatrix.c\
				Core/VBMatrix2D.c\
				Core/VBMatrix2DWrapper.c\
				Core/VBMatrix3D.c\
				Core/VBQuadtree.c\
				Core/VBString.c\
				Core/VBTriangle.c\
				Core/VBTriangle2D.c\
				Core/VBVector.c\
				Core/VBVector2D.c\
				Core/VBVector3D.c\
				Display/VBBlendMode.c\
				Display/VBDrawable.c\
				Display/VBDrawable2D.c\
				Display/VBDrawable3D.c\
				Display/VBGraphic.c\
				Display/VBGraphic2D.c\
				Display/VBGraphic3D.c\
				Display/VBImage.c\
				Display/VBModel.c\
				Display/VBModel2D.c\
				Display/VBModel3D.c\
				Display/VBTexture.c\
				IO/VBFile.c\
				IO/VBJPEGFile.c\
				IO/VBObjectFile.c\
				IO/VBObjectFile2D.c\
				IO/VBObjectFile2DFrame.c\
				IO/VBObjectFile2DKeyFrame.c\
				IO/VBObjectFile2DKeyFrameElement.c\
				IO/VBObjectFile2DLibrary.c\
				IO/VBObjectFile2DLibraryNameID.c\
				IO/VBObjectFile2DTexcoord.c\
				IO/VBObjectFile2DTransition.c\
				IO/VBObjectFile3D.c\
				IO/VBPNGFile.c\
				IO/VBSystem.c\
				IO/VBTouch.c\
				IO/VBThread.c\
				Other/Box2D/Collision/b2BroadPhase.cpp\
				Other/Box2D/Collision/b2CollideCircle.cpp\
				Other/Box2D/Collision/b2CollidePolygon.cpp\
				Other/Box2D/Collision/b2Collision.cpp\
				Other/Box2D/Collision/b2Distance.cpp\
				Other/Box2D/Collision/b2DynamicTree.cpp\
				Other/Box2D/Collision/b2TimeOfImpact.cpp\
				Other/Box2D/Collision/Shapes/b2CircleShape.cpp\
				Other/Box2D/Collision/Shapes/b2PolygonShape.cpp\
				Other/Box2D/Common/b2BlockAllocator.cpp\
				Other/Box2D/Common/b2Math.cpp\
				Other/Box2D/Common/b2Settings.cpp\
				Other/Box2D/Common/b2StackAllocator.cpp\
				Other/Box2D/Dynamics/b2Body.cpp\
				Other/Box2D/Dynamics/b2ContactManager.cpp\
				Other/Box2D/Dynamics/b2Fixture.cpp\
				Other/Box2D/Dynamics/b2Island.cpp\
				Other/Box2D/Dynamics/b2World.cpp\
				Other/Box2D/Dynamics/b2WorldCallbacks.cpp\
				Other/Box2D/Dynamics/Contacts/b2CircleContact.cpp\
				Other/Box2D/Dynamics/Contacts/b2Contact.cpp\
				Other/Box2D/Dynamics/Contacts/b2ContactSolver.cpp\
				Other/Box2D/Dynamics/Contacts/b2PolygonAndCircleContact.cpp\
				Other/Box2D/Dynamics/Contacts/b2PolygonContact.cpp\
				Other/Box2D/Dynamics/Contacts/b2TOISolver.cpp\
				Other/Box2D/Dynamics/Joints/b2DistanceJoint.cpp\
				Other/Box2D/Dynamics/Joints/b2FrictionJoint.cpp\
				Other/Box2D/Dynamics/Joints/b2GearJoint.cpp\
				Other/Box2D/Dynamics/Joints/b2Joint.cpp\
				Other/Box2D/Dynamics/Joints/b2LineJoint.cpp\
				Other/Box2D/Dynamics/Joints/b2MouseJoint.cpp\
				Other/Box2D/Dynamics/Joints/b2PrismaticJoint.cpp\
				Other/Box2D/Dynamics/Joints/b2PulleyJoint.cpp\
				Other/Box2D/Dynamics/Joints/b2RevoluteJoint.cpp\
				Other/Box2D/Dynamics/Joints/b2WeldJoint.cpp\
				Other/jpeg/jcapimin.c\
				Other/jpeg/jcapistd.c\
				Other/jpeg/jccoefct.c\
				Other/jpeg/jccolor.c\
				Other/jpeg/jcdctmgr.c\
				Other/jpeg/jchuff.c\
				Other/jpeg/jcinit.c\
				Other/jpeg/jcmainct.c\
				Other/jpeg/jcmarker.c\
				Other/jpeg/jcmaster.c\
				Other/jpeg/jcomapi.c\
				Other/jpeg/jcparam.c\
				Other/jpeg/jcphuff.c\
				Other/jpeg/jcprepct.c\
				Other/jpeg/jcsample.c\
				Other/jpeg/jdapimin.c\
				Other/jpeg/jdapistd.c\
				Other/jpeg/jdatadst.c\
				Other/jpeg/jdatasrc.c\
				Other/jpeg/jdcoefct.c\
				Other/jpeg/jdcolor.c\
				Other/jpeg/jddctmgr.c\
				Other/jpeg/jdhuff.c\
				Other/jpeg/jdinput.c\
				Other/jpeg/jdmainct.c\
				Other/jpeg/jdmarker.c\
				Other/jpeg/jdmaster.c\
				Other/jpeg/jdmerge.c\
				Other/jpeg/jdphuff.c\
				Other/jpeg/jdpostct.c\
				Other/jpeg/jdsample.c\
				Other/jpeg/jdtrans.c\
				Other/jpeg/jerror.c\
				Other/jpeg/jfdctflt.c\
				Other/jpeg/jfdctfst.c\
				Other/jpeg/jfdctint.c\
				Other/jpeg/jidctflt.c\
				Other/jpeg/jidctfst.c\
				Other/jpeg/jidctint.c\
				Other/jpeg/jidctred.c\
				Other/jpeg/jmemansi.c\
				Other/jpeg/jmemmgr.c\
				Other/jpeg/jquant1.c\
				Other/jpeg/jquant2.c\
				Other/jpeg/jutils.c\
				Other/png/png.c\
				Other/png/pngerror.c\
				Other/png/pnggccrd.c\
				Other/png/pngget.c\
				Other/png/pngmem.c\
				Other/png/pngpread.c\
				Other/png/pngread.c\
				Other/png/pngrio.c\
				Other/png/pngrtran.c\
				Other/png/pngrutil.c\
				Other/png/pngset.c\
				Other/png/pngtrans.c\
				Other/png/pngvcrd.c\
				Other/png/pngwio.c\
				Other/png/pngwrite.c\
				Other/png/pngwtran.c\
				Other/png/pngwutil.c\
				Other/theora/apiwrapper.c\
				Other/theora/bitpack.c\
				Other/theora/decapiwrapper.c\
				Other/theora/decinfo.c\
				Other/theora/decode.c\
				Other/theora/dequant.c\
				Other/theora/fragment.c\
				Other/theora/huffdec.c\
				Other/theora/idct.c\
				Other/theora/info.c\
				Other/theora/internal.c\
				Other/theora/quant.c\
				Other/theora/state.c\
				Other/vorbis/analysis.c\
				Other/vorbis/bitrate.c\
				Other/vorbis/bitwise.c\
				Other/vorbis/block.c\
				Other/vorbis/codebook.c\
				Other/vorbis/envelope.c\
				Other/vorbis/floor0.c\
				Other/vorbis/floor1.c\
				Other/vorbis/framing.c\
				Other/vorbis/info.c\
				Other/vorbis/lookup.c\
				Other/vorbis/lpc.c\
				Other/vorbis/lsp.c\
				Other/vorbis/mapping0.c\
				Other/vorbis/mdct.c\
				Other/vorbis/psy.c\
				Other/vorbis/registry.c\
				Other/vorbis/res0.c\
				Other/vorbis/sharedbook.c\
				Other/vorbis/smallft.c\
				Other/vorbis/synthesis.c\
				Other/vorbis/vorbisfile.c\
				Other/vorbis/window.c\
				Other/zlib/adler32.c\
				Other/zlib/compress.c\
				Other/zlib/crc32.c\
				Other/zlib/deflate.c\
				Other/zlib/gzio.c\
				Other/zlib/infback.c\
				Other/zlib/inffast.c\
				Other/zlib/inflate.c\
				Other/zlib/inftrees.c\
				Other/zlib/ioapi.c\
				Other/zlib/trees.c\
				Other/zlib/uncompr.c\
				Other/zlib/unzip.c\
				Other/zlib/zutil.c\
				Util/VBDebug.c\
				Util/VBTween.c\
				VBDisplay2D.c\
				VBDisplay3D.c\
				VBEngine.c\
				VBEngineFileInfo.c\
				VBType.c\
	

LOCAL_LDLIBS := -lz

#include $(BUILD_SHARED_LIBRARY)
include $(BUILD_STATIC_LIBRARY)
