package com.vanillabreeze.util;

public class XMLData {
	public int stages;
	public int icecreamball[] = new int[12];
	public int icecreamballTwo[] = new int[12];
	public int icecreamPattern[] = new int[12];
	public int icecreamPatternTwo[] = new int[12];
	public int icecreamEye[] = new int[8];
	public int icecreamEyeTwo[] = new int[8];
	public int icenum;
	public boolean icepattern;
	public boolean icepatterntwo;
	public boolean iceeyes;
	public boolean iceeyestwo;
	public int milkcream;
	public int cherry;
	public int chocochips;
	public int nuts;
	public int candy;
	public int leftspoid;
	public int rightspoid;
	public int iceice;
	public int leftcorncount;
	public int leftcorn_v;
	public int leftcorn_c;
	public int leftcorn_b;
	public int leftcorn_g;
	public int rightcorncount;
	public int rightcorn_v;
	public int rightcorn_c;
	public int rightcorn_b;
	public int rightcorn_g;
	public int centercorncount;
	public int centercorn_v;
	public int centercorn_c;
	public int centercorn_b;
	public int centercorn_g;
	public boolean TUB_BIG_VANILLA;
	public boolean TUB_BIG_CHOCO;
	public boolean TUB_BIG_BERRY;
	public boolean TUB_BIG_GREEN;
	public boolean TUB_SMALL_VANILLA;
	public boolean TUB_SMALL_CHOCO;
	public boolean TUB_SMALL_BERRY;
	public boolean TUB_SMALL_GREEN;
	public boolean SPOON_H_VANILLA;
	public boolean SPOON_H_CHOCO;
	public boolean SPOON_H_BERRY;
	public boolean SPOON_H_GREEN;
	public boolean SPOON_L_VANILLA;
	public boolean SPOON_L_CHOCO;
	public boolean SPOON_L_BERRY;
	public boolean SPOON_L_GREEN;
	public boolean SPOON_R_VANILLA;
	public boolean SPOON_R_CHOCO;
	public boolean SPOON_R_BERRY;
	public boolean SPOON_R_GREEN;
	public boolean RING_VERTICAL;
	public boolean RING_HORIZON;
	public boolean SUNGLASS;
	public boolean CAP_OBJ;
	public boolean ICE_OBJ;
	public boolean PATTERN_CAST;
	public boolean MIX_OBJ;
	public boolean MASK_OBJ;
	public boolean CenterMilkCream;
	public boolean CenterCherry;
	public boolean CenterChocochips;
	public boolean CenterNuts;
	public boolean CenterCandy;
	public boolean CenterSpoid_v;
	public boolean CenterSpoid_c;
	public boolean CenterSpoid_b;
	public boolean CenterSpoid_g;
	public float DefaultTime;
	public int DefaultMove;  // unsigned int 
}
